# Generated by Django 2.2.3 on 2022-08-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Contenido',
            new_name='contenido',
        ),
    ]
